var interns = [
    {
        firstName: 'Abdoul',
        lastName: 'Barry',
        folderName: 'abdoul_barry',
        fileName: 'barry.html',
        imgName: 'pic.jpg',
        company: 'FOAM',
        year: 2018,
    },
    {
        firstName: 'Abdul',
        lastName: 'Manan',
        folderName: 'abdul_manan',
        fileName: 'abdul.html',
        imgName: '../../assets/site/profile-placeholder.png',
        company: 'Microsoft',
        year: 2018,
    },
    {
        firstName: 'Andrea',
        lastName: 'Cajamarca',
        folderName: 'andrea-cajamarca',
        fileName: 'andrea.html',
        imgName: 'andreac01.jpg',
        company: 'Animoto',
        year: 2018,
    },
    {
        firstName: 'Anthony',
        lastName: 'Yang',
        folderName: 'anthony_yang',
        fileName: 'anthony.html',
        imgName: 'anthony.JPG',
        company: 'Accenture (Shiseido)',
        year: 2018,
    },
    {
        firstName: 'Ashley',
        lastName: 'Diaz',
        folderName: 'ashley-diaz',
        fileName: 'ashley.html',
        imgName: 'ashley_headshot.jpg',
        company: 'American Express',
        year: 2018,
    },
    {
        firstName: 'Azwad',
        lastName: 'Shameem',
        folderName: 'azwad',
        fileName: 'azwad.html',
        imgName: 'azwad.jpg',
        company: 'HSBC',
        year: 2018,
    },
    {
        firstName: 'Brittany',
        lastName: 'Torres',
        folderName: 'Brittany_Torres',
        fileName: 'brittany.html',
        imgName: 'picture.PNG',
        company: 'Group Nine Media',
        year: 2018,
    },
    {
        firstName: 'Carmen',
        lastName: 'Salas',
        folderName: 'carmen_salas',
        fileName: 'carmen.html',
        imgName: 'download.png',
        company: 'Valtech',
        year: 2018,
    },
    {
        firstName: 'Coral',
        lastName: 'Reyes',
        folderName: 'coral_reyes',
        fileName: 'coral.html',
        imgName: 'icon.jpg',
        company: 'Oscar Health',
        year: 2018,
    },
    {
        firstName: 'Daniel',
        lastName: 'Zamilatskiy',
        folderName: 'daniel_z',
        fileName: 'daniel.html',
        imgName: '../../assets/site/profile-placeholder.png',
        company: 'FOAM',
        year: 2018,
    },
    {
        firstName: 'DeAngelo',
        lastName: 'Dove',
        folderName: 'deangelo_dove',
        fileName: 'deangelo.html',
        imgName: '../../assets/site/profile-placeholder.png',
        company: 'Salesforce',
        year: 2018,
    },
    {
        firstName: 'Imani',
        lastName: 'Greenidge',
        folderName: 'imani_greenidge',
        fileName: 'imani.html',
        imgName: 'imani1.jpg',
        company: 'Policygenius',
        year: 2018,
    },
    {
        firstName: 'Jason',
        lastName: 'Alvarez',
        folderName: 'jason_alvarez',
        fileName: 'jason.html',
        imgName: '../../assets/site/profile-placeholder.png',
        company: 'ATTCK',
        year: 2018,
    },
    {
        firstName: 'Jason',
        lastName: 'Giang',
        folderName: 'jason_giang',
        fileName: 'jason.html',
        imgName: '../../assets/site/profile-placeholder.png',
        company: 'TPG',
        year: 2018,
    },
    {
        firstName: 'Jennifer',
        lastName: 'Zheng',
        folderName: 'jennifer_zheng',
        fileName: 'jennnifer.html',
        imgName: 'jennifer.png',
        company: 'HSBC',
        year: 2018,
    },
    {
        firstName: 'Jackie',
        lastName: 'He',
        folderName: 'jiaqi_he',
        fileName: 'jiaqi.html',
        imgName: 'IMG_9799 (2).jpeg',
        company: 'Group Nine Media',
        year: 2018,
    },
    {
        firstName: 'Jocelyn',
        lastName: 'Reyes',
        folderName: 'jocelyn_reyes',
        fileName: 'jocelyn.html',
        imgName: 'jocelyn.jpg',
        company: 'Datadog',
        year: 2018,
    },
    {
        firstName: 'Jordan',
        lastName: 'Kelly',
        folderName: 'jordan_kelly',
        fileName: 'jordan.html',
        imgName: '../../assets/site/profile-placeholder.png',
        company: 'OpenFin',
        year: 2018,
    },
    {
        firstName: 'Julian',
        lastName: 'Jimenez',
        folderName: 'julian_jimenez',
        fileName: 'julian_jimenez.html',
        imgName: 'julian.jpg',
        company: 'Oscar Health',
        year: 2018,
    },
    {
        firstName: 'Kayahma',
        lastName: 'Brown',
        folderName: 'Kayahma',
        fileName: 'Kayahma.html',
        imgName: 'kay.jpg',
        company: 'Etsy',
        year: 2018,
    },
    {
        firstName: 'Kevin',
        lastName: 'Hui',
        folderName: 'kevin_hui',
        fileName: 'kevin.html',
        imgName: 'kevin.jpg',
        company: 'MediaMath',
        year: 2018,
    },
    {
        firstName: 'Kiara',
        lastName: 'Correa Acosta',
        folderName: 'Kiara_Correa_Acosta',
        fileName: 'Kiara.html',
        imgName: 'Kiara.png',
        company: 'Rent the Runway',
        year: 2018,
    },
    {
        firstName: 'Layla',
        lastName: 'Flight',
        folderName: 'layla_flight',
        fileName: 'layla.html',
        imgName: '../../assets/site/profile-placeholder.png',
        company: 'Animoto',
        year: 2018,
    },
    {
        firstName: 'Lissette',
        lastName: 'Duran',
        folderName: 'lissette_duran',
        fileName: 'lissette.html',
        imgName: 'lissettepic.jpg',
        company: 'MakeSpace',
        year: 2018,
    },
    {
        firstName: 'Louis',
        lastName: 'Gabrie',
        folderName: 'louis_gabrie',
        fileName: 'louis.html',
        imgName: 'portfolio_me.jpg',
        company: 'ALICE',
        year: 2018,
    },
    {
        firstName: 'Mark',
        lastName: 'Griffith',
        folderName: 'mark_griffith',
        fileName: 'markgriffith.html',
        imgName: 'mark.jpg',
        company: 'MediaMath',
        year: 2018,
    },
    {
        firstName: 'Michal',
        lastName: 'Idzik',
        folderName: 'michal_idzik',
        fileName: 'michal.html',
        imgName: 'michal.jpg',
        company: 'OpenFin',
        year: 2018,
    },
    {
        firstName: 'Momina',
        lastName: 'Fazal',
        folderName: 'momina_fazal',
        fileName: 'momina.html',
        imgName: 'momina.jpg',
        company: 'OkCupid',
        year: 2018,
    },
    {
        firstName: 'Monserrat',
        lastName: 'Diaz Martinez',
        folderName: 'monserrat_diazmartinez',
        fileName: 'monserrat.html',
        imgName: 'headshot2.jpg',
        company: 'Vaan Group',
        year: 2018,
    },
    {
        firstName: 'Oscar',
        lastName: 'Ramirez',
        folderName: 'oscar_ramirez',
        fileName: 'oscar.html',
        imgName: '../../assets/site/profile-placeholder.png',
        company: 'Frame.io',
        year: 2018,
    },
    {
        firstName: 'Patricia',
        lastName: 'Perez',
        folderName: 'patricia_perez',
        fileName: 'patricia.html',
        imgName: 'patricia.JPG',
        company: 'FTI Consulting',
        year: 2018,
    },
    {
        firstName: 'Ramata',
        lastName: 'Williams',
        folderName: 'ramata_williams',
        fileName: 'ramata.html',
        imgName: 'ramata.jpg',
        company: 'American Express',
        year: 2018,
    },
    {
        firstName: 'Stephanie',
        lastName: 'Smith',
        folderName: 'Stephanie_Smith',
        fileName: 'Stephanie.html',
        imgName: 'Stephanie.jpg',
        company: 'Valtech',
        year: 2018,
    },
    {
        firstName: 'Steven',
        lastName: 'Rosario',
        folderName: 'steven_rosario',
        fileName: 'stevenrosario.html',
        imgName: 'headshot.jpg',
        company: 'Accenture',
        year: 2018,
    },
    {
        firstName: 'Tai',
        lastName: 'Chowdhury',
        folderName: 'Taifinkaba_Chowdhury',
        fileName: 'Taifinkaba.html',
        imgName: 'Taifinkaba.jpg',
        company: 'American Express',
        year: 2018,
    },
    {
        firstName: 'Thomas',
        lastName: 'Perez',
        folderName: 'thomas_perez',
        fileName: 'thomas.html',
        imgName: 'thomas.JPG',
        company: 'Slice',
        year: 2018,
    },
    {
        firstName: 'Wendy',
        lastName: 'Jiang',
        folderName: 'wendy_jiang',
        fileName: 'wendy.html',
        imgName: 'wendy.JPG',
        company: 'Rent the Runway',
        year: 2018,
    },
    {
        firstName: 'Wuqian',
        lastName: 'Ye',
        folderName: 'wuqian_ye',
        fileName: 'wuqian.html',
        imgName: '../../assets/site/profile-placeholder.png',
        company: 'Etsy',
        year: 2018,
    },
    {
        firstName: 'FirstName',
        lastName: 'LastName',
        folderName: '',
        fileName: '',
        imgName: '../../assets/site/profile-placeholder.png',
        company: 'Company',
        year: 2018,
    },
];
